project:
  type: website

website:
  title: "CSC 444 Fall 2022"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - schedule.qmd
      - assignments.qmd 

format:
  html:
    theme:
      light: United
      dark: slate
    css: styles.css
    toc: true



